# Generated by Django 5.1.4 on 2024-12-30 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_viaje', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='equipaje',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='equipaje',
            name='email',
        ),
        migrations.RemoveField(
            model_name='equipaje',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='estadia',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='estadia',
            name='email',
        ),
        migrations.RemoveField(
            model_name='estadia',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='estadia',
            name='profesion',
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='nombre',
        ),
    ]
